data_path: "/Users/samdeblank/Library/CloudStorage/OneDrive-PrinsesMaximaCentrum/github/BEHAV3D/scripts/data_processing/test/testdata.tiff"
output_dir: "/Users/samdeblank/Library/CloudStorage/OneDrive-PrinsesMaximaCentrum/github/BEHAV3D/scripts/data_processing/test"

ilastik_path: "/Applications/ilastik-1.4.0b27-OSX.app/Contents/ilastik-release/run_ilastik.sh"
ilastik_pixel_classifier_model: "/Users/samdeblank/Library/CloudStorage/OneDrive-PrinsesMaximaCentrum/github/BEHAV3D/scripts/data_processing/ilastik/AIM_MB2_pix_clas_v5.ilp"
ilastik_object_classifier_model: "/Users/samdeblank/Library/CloudStorage/OneDrive-PrinsesMaximaCentrum/github/BEHAV3D/scripts/data_processing/ilastik/AIM_MB2_obj_clas_v4.ilp"
ilastik_object_postprocessing_model: "/Users/samdeblank/Library/CloudStorage/OneDrive-PrinsesMaximaCentrum/github/BEHAV3D/scripts/data_processing/ilastik/AIM_MB2_faketrack_obj_split_v4.ilp"

trackmate_path: ""
