data_dir: /Users/samdeblank/OneDrive - Prinses Maxima Centrum/github/BEHAV3D-2.0//demos/tcell_demo/data
output_dir: /Users/samdeblank/OneDrive - Prinses Maxima Centrum/github/BEHAV3D-2.0//demos/tcell_demo/example_output
metadata_csv_path: /Users/samdeblank/OneDrive - Prinses Maxima Centrum/github/BEHAV3D-2.0//demos/tcell_demo/BEHAV3D_metadata.tsv
randomforest_path: /Users/samdeblank/OneDrive - Prinses Maxima Centrum/github/BEHAV3D-2.0//references/TrainedRandomForest.Rdata
tcell_exp_duration: 400
tcell_min_track_length: 60
tcell_max_track_length: 60
organoid_min_volume: 1000
organoid_min_track_length: 40
organoid_exp_duration: 300
umap_minimal_distance: 0.1
umap_n_neighbors: 5
nr_of_clusters: 6
first_1: 86
first_2: 95
second_1: 145
second_2: 154
scRNAseq_dataset: /Users/samdeblank/OneDrive - Prinses Maxima Centrum/github/BEHAV3D-2.0//demos/tcell_demo/data/scRNA_seq_dataset.rds
